name: Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --python ${{ matrix.python_version }} --dev
    - name: Test with pytest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pipenv run pytest --cov=airflow_provider_nessie/
        pipenv run codecov
    - name: Lint
      if: matrix.python_version == 3.7
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pipenv run flake8 airflow_provider_nessie tests --exclude "airflow_provider_nessie/example_dags/*"
        pipenv run mypy --ignore-missing-imports -p airflow_provider_nessie
  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Release on PyPI
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
      run: |
        pipenv run flit publish
